# Generated by Django 5.0.3 on 2024-03-19 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('inside', models.BooleanField(default=True)),
                ('water', models.CharField(max_length=200)),
                ('sun', models.CharField(max_length=200)),
                ('fertilization', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('pet', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('inside', models.BooleanField(default=True)),
                ('water', models.CharField(max_length=200)),
                ('sun', models.CharField(max_length=200)),
                ('fertilization', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
