# Generated by Django 5.0.3 on 2024-04-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=75)),
                ('last_name', models.CharField(blank=True, default='', max_length=75)),
                ('email', models.EmailField(blank=True, default='', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='fertilization',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='personalplant',
            name='water',
        ),
        migrations.AddField(
            model_name='personalplant',
            name='plantID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.libraryplant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libraryplant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalplant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
