# Generated by Django 5.0.4 on 2024-05-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_personalplant_plantid_alter_personalplant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalplant',
            name='last_water',
            field=models.DateField(auto_now=True),
        ),
    ]
