# Generated by Django 5.0.3 on 2024-04-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_libraryplant_id_alter_personalplant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplant',
            name='user',
        ),
    ]
