# Generated by Django 5.0.3 on 2024-04-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_libraryplant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplant',
            name='scientific_name',
        ),
    ]
